### ISSUE TITLE
pip does not install dependencies

### ISSUE THREAD

**Issue by DrJonnyT** [wesselb/neuralprocesses#17]
If I run this:
conda create -n neuralproc
conda activate neuralproc
pip install neuralprocesses

I end up with neuralprocesses installed but dependencies like tensorflow or pytorch are missing. Should they be installed?

**Comment by wesselb** [comment]
Hey @DrJonnyT! All dependencies except for the linear-algebra backend should be installed automatically.

If you want to use the package with PyTorch, you will need to additionally install PyTorch (`pip install torch`). If you want to use the package with TensorFlow, you will need to additionally install TensorFlow and TF Probability (`pip install tensorflow tensorflow-probability`).

The reason why PyTorch and TF aren't automatically installed is that you can choose which one to install: users of PyTorch shouldn't be forced to install TF and _vice versa_.

I'm sorry if this wasn't clear!

**Comment by DrJonnyT** [comment]
Aha cool, I did wonder if it was deliberate. Maybe it would be useful to say that in the readme? Cheers!

**Comment by wesselb** [comment]
@DrJonnyT I've now written this explicitly in the README. Thank you for the suggestion! :)
